# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VK_User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('photo_rec_url', models.CharField(max_length=200)),
                ('have_active_post', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
