# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vk_user',
            name='last_point',
            field=models.CharField(default='', max_length=50),
        ),
    ]
