# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160918_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VKUser',
            new_name='VK_User',
        ),
    ]
