# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160918_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='vk_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vk_user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
