# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20160918_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_rec', models.CharField(max_length=200)),
                ('has_active_post', models.BooleanField(default=False)),
                ('last_point', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='VK_User',
        ),
    ]
