# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_vkuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('pub_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_actual', models.BooleanField(default=True)),
                ('users_liked_ids', models.CharField(max_length=50)),
            ],
        ),
    ]
