# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkuser',
            name='last_point',
        ),
        migrations.AddField(
            model_name='vkuser',
            name='last_place',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='place',
            field=models.CharField(default='', max_length=200),
        ),
    ]
