# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-02 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vkuser_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
