# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20170204_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.get_image_path),
        ),
    ]
