# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20170223_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='last_place',
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='place',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1),
        ),
    ]
