# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20170223_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_liked_ids',
        ),
        migrations.AddField(
            model_name='like',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
