# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20170226_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hash_id',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
