# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-27 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20170326_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='about',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
