# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_vkuser_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.get_image_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.Post')),
            ],
        ),
    ]
