# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
