# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20170331_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hash_id',
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.IntegerField(choices=[(0, '\u0421\u0435\u0432\u0430\u0441\u0442\u043e\u043f\u043e\u043b\u044c'), (1, '\u0421\u0438\u043c\u0444\u0435\u0440\u043e\u043f\u043e\u043b\u044c'), (2, '\u042f\u043b\u0442\u0430')], default=1),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
