# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20170422_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
