# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20170422_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.Tag'),
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
