# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20170502_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
