# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_auto_20170502_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.IntegerField(choices=[(-1, ''), (0, '\u0421\u0435\u0432\u0430\u0441\u0442\u043e\u043f\u043e\u043b\u044c'), (1, '\u0421\u0438\u043c\u0444\u0435\u0440\u043e\u043f\u043e\u043b\u044c'), (2, '\u042f\u043b\u0442\u0430')], default=-1),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag_id',
            field=models.IntegerField(choices=[(-1, ''), (0, '\u0438\u0449\u0443 \u043f\u0430\u0440\u043d\u044f'), (1, '\u0438\u0449\u0443 \u0434\u0435\u0432\u0443\u0448\u043a\u0443'), (2, '\u0438\u0449\u0443 \u0434\u0440\u0443\u0433\u0430'), (3, '\u0438\u0449\u0443 \u043f\u043e\u0434\u0440\u0443\u0433\u0443'), (4, '\u0438\u0449\u0443 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044e'), (5, '\u0438\u0449\u0443 \u0441/\u043e')], default=-1),
        ),
    ]
