# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20170502_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
