# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-08 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0039_auto_20170502_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKUserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.IntegerField(choices=[(-1, ''), (0, '\u043b\u0430\u0439\u043a'), (1, '\u043f\u043e\u0441\u043b\u0430\u043d\u0438\u0435'), (2, '\u043f\u043e\u0441\u0442 \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'), (4, '\u043f\u043e\u0441\u0442 \u0443\u0434\u0430\u043b\u0435\u043d'), (5, '\u043f\u043e\u0441\u0442 \u043d\u0435 \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d')], default=-1)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
