# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_auto_20170508_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
