# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='sex',
            field=models.IntegerField(choices=[(-1, '\u043d\u0435 \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u043e'), (0, '\u043f\u0430\u0440\u0435\u043d\u044c'), (1, '\u0434\u0435\u0432\u0443\u0448\u043a\u0430')], default=-1),
        ),
    ]
