# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_vkuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='notification_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='notifications_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
