# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_auto_20170515_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkuser',
            name='notification_amount',
        ),
    ]
