# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_notification_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='has_closed_attention',
            field=models.BooleanField(default=False),
        ),
    ]
