# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_vkuser_has_closed_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[(-1, 'no'), (0, 'like'), (1, 'message'), (2, 'accepted'), (3, 'rejected')], default=-1, max_length=20),
        ),
    ]
