# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_auto_20170522_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='verb_long',
            field=models.CharField(default='', max_length=255),
        ),
    ]
