# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-01 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0058_auto_20170523_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-accepted_datetime']},
        ),
        migrations.AddField(
            model_name='post',
            name='accepted_datetime',
            field=models.DateTimeField(null=True, verbose_name='\u041e\u0434\u043e\u0431\u0440\u0435\u043d\u043e'),
        ),
    ]
