# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0059_auto_20170601_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_actual',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='has_active_post',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='notifications_timestamp',
        ),
        migrations.AddField(
            model_name='vkuser',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='\u041f\u043e\u0441\u0442'),
        ),
    ]
