# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0061_auto_20170602_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
