# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-11 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_vkuser_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_datetime']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='accepted_datetime',
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.IntegerField(choices=[(-1, 'no'), (0, '\u043b\u0430\u0439\u043a\u043d\u0443{} \u0432\u0430\u0448 \u043f\u043e\u0441\u0442.'), (1, '\u043e\u0441\u0442\u0430\u0432\u0438{} \u043f\u043e\u0441\u043b\u0430\u043d\u0438\u0435 \u043a \u0432\u0430\u0448\u0435\u043c\u0443 \u043f\u043e\u0441\u0442\u0443.'), (2, '\u0412\u0430\u0448 \u043f\u043e\u0441\u0442 \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d.'), (3, '\u0412\u0430\u0448 \u043f\u043e\u0441\u0442 \u043d\u0430\u0440\u0443\u0448\u0430\u0435\u0442 \u043f\u0440\u0430\u0432\u0438\u043b\u0430 \u0441\u0430\u0439\u0442\u0430, \u043f\u043e\u044d\u0442\u043e\u043c\u0443 \u043e\u043d \u043d\u0435 \u0431\u0443\u0434\u0435\u0442 \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d.')], default=-1),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post'),
        ),
    ]
