# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0065_auto_20170618_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='postimage',
            name='has_post',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u0438\u043a\u0440\u0435\u043f\u043b\u0435\u043d\u043e'),
        ),
    ]
