# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-07 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0066_auto_20170705_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name_plural': '\u0427\u0435\u0440\u043d\u044b\u0439 \u0441\u043f\u0438\u0441\u043e\u043a'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_datetime'], 'verbose_name_plural': '\u041f\u043e\u0441\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='vkuser',
            options={'verbose_name_plural': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438'},
        ),
    ]
