# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-07 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0067_auto_20170707_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='\u0411\u0440\u044d\u043d\u0434')),
                ('brand_icon', models.ImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path)),
                ('text', models.CharField(max_length=2000, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('place', models.IntegerField(choices=[(-1, '\u0412\u0441\u0435'), (0, '\u0421\u0435\u0432\u0430\u0441\u0442\u043e\u043f\u043e\u043b\u044c'), (1, '\u0421\u0438\u043c\u0444\u0435\u0440\u043e\u043f\u043e\u043b\u044c'), (2, '\u042f\u043b\u0442\u0430')], default=-1, verbose_name='\u041c\u0435\u0441\u0442\u043e')),
                ('pub_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e')),
                ('accepted', models.BooleanField(default=False, verbose_name='\u041e\u0434\u043e\u0431\u0440\u0435\u043d\u043e')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path)),
            ],
            options={
                'verbose_name_plural': '\u0420\u0435\u043a\u043b\u0430\u043c\u0430',
            },
        ),
    ]
