# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-07 19:28
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0068_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': '\u0420\u0435\u043a\u043b\u0430\u043c\u0443', 'verbose_name_plural': '\u0420\u0435\u043a\u043b\u0430\u043c\u0430'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='image1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image6',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
