# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0069_auto_20170707_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image6',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=posts.models.get_ad_image_path),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=posts.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='sex',
            field=models.IntegerField(choices=[(2, '\u043f\u0430\u0440\u0435\u043d\u044c'), (1, '\u0434\u0435\u0432\u0443\u0448\u043a\u0430')], default=-1, verbose_name='\u041f\u043e\u043b'),
        ),
    ]
