# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0072_auto_20170711_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mark_read',
            field=models.BooleanField(default=False),
        ),
    ]
