# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0073_notification_mark_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actor_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
