# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0074_auto_20170711_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='actor_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='actor_object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.VKUser'),
        ),
    ]
