# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-12 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0077_vkuser_photo_large'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkuser',
            name='photo_large',
        ),
    ]
