# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-19 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0079_auto_20170718_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.IntegerField(choices=[(-1, 'no'), (0, '\u043b\u0430\u0439\u043a\u043d\u0443{} \u0432\u0430\u0448 <a href="{}\u043f\u043e\u0441\u0442\u044b/\u043c\u043e\u0439" class="w3-text-blue link-no-style classic-hover" title="\u0421\u043f\u0438\u0441\u043e\u043a \u043b\u044e\u0434\u0435\u0439, \u043a\u043e\u0442\u043e\u0440\u044b\u043c \u043f\u043e\u043d\u0440\u0430\u0432\u0438\u043b\u0441\u044f \u043f\u043e\u0441\u0442.">\u043f\u043e\u0441\u0442</a>.'), (1, '\u043e\u0441\u0442\u0430\u0432\u0438{} \u0432\u0430\u043c <a href="{}\u043f\u043e\u0441\u0442\u044b/\u043f\u043e\u043d\u0440\u0430\u0432\u0438\u043b\u043e\u0441\u044c?post_id={}" class="w3-text-blue link-no-style classic-hover" title="\u0421\u043f\u0438\u0441\u043e\u043a \u043b\u044e\u0434\u0435\u0439, \u043a\u043e\u0442\u043e\u0440\u044b\u043c \u043f\u043e\u043d\u0440\u0430\u0432\u0438\u043b\u0441\u044f \u043f\u043e\u0441\u0442.">\u043f\u043e\u0441\u043b\u0430\u043d\u0438\u0435</a>.'), (2, '\u0412\u0430\u0448 <a href="{}\u043f\u043e\u0441\u0442\u044b/\u043c\u043e\u0439" class="w3-text-blue link-no-style classic-hover" title="\u0421\u043f\u0438\u0441\u043e\u043a \u043b\u044e\u0434\u0435\u0439, \u043a\u043e\u0442\u043e\u0440\u044b\u043c \u043f\u043e\u043d\u0440\u0430\u0432\u0438\u043b\u0441\u044f \u043f\u043e\u0441\u0442.">\u043f\u043e\u0441\u0442</a> \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d.'), (3, '\u0412\u0430\u0448 <a href="{}\u043f\u043e\u0441\u0442\u044b/\u043c\u043e\u0439" class="w3-text-blue link-no-style classic-hover" title="\u0421\u043f\u0438\u0441\u043e\u043a \u043b\u044e\u0434\u0435\u0439, \u043a\u043e\u0442\u043e\u0440\u044b\u043c \u043f\u043e\u043d\u0440\u0430\u0432\u0438\u043b\u0441\u044f \u043f\u043e\u0441\u0442.">\u043f\u043e\u0441\u0442</a> \u043d\u0430\u0440\u0443\u0448\u0430\u0435\u0442 \u043f\u0440\u0430\u0432\u0438\u043b\u0430 \u0441\u0430\u0439\u0442\u0430, \u043f\u043e\u044d\u0442\u043e\u043c\u0443 \u043e\u043d \u043d\u0435 \u0431\u0443\u0434\u0435\u0442 \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d.')], default=-1),
        ),
    ]
