# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0082_auto_20170722_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='place',
            field=models.IntegerField(choices=[(-1, '\u0412\u0441\u0435'), (0, '\u0421\u0435\u0432\u0430\u0441\u0442\u043e\u043f\u043e\u043b\u044c'), (1, '\u0421\u0438\u043c\u0444\u0435\u0440\u043e\u043f\u043e\u043b\u044c'), (2, '\u042f\u043b\u0442\u0430')], db_index=True, default=-1, verbose_name='\u041c\u0435\u0441\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='unread',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(db_index=True, default=True, verbose_name='\u0410\u043d\u043e\u043d\u0438\u043c\u043d\u044b\u0439?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.IntegerField(choices=[(-1, ''), (0, '\u0421\u0435\u0432\u0430\u0441\u0442\u043e\u043f\u043e\u043b\u044c'), (1, '\u0421\u0438\u043c\u0444\u0435\u0440\u043e\u043f\u043e\u043b\u044c'), (2, '\u042f\u043b\u0442\u0430')], db_index=True, default=-1, verbose_name='\u041c\u0435\u0441\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.IntegerField(choices=[(-1, ''), (0, '\u0438\u0449\u0443 \u043f\u0430\u0440\u043d\u044f'), (1, '\u0438\u0449\u0443 \u0434\u0435\u0432\u0443\u0448\u043a\u0443'), (2, '\u0438\u0449\u0443 \u0434\u0440\u0443\u0433\u0430'), (3, '\u0438\u0449\u0443 \u043f\u043e\u0434\u0440\u0443\u0433\u0443'), (4, '\u0438\u0449\u0443 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044e'), (5, '\u0438\u0449\u0443 \u0441/\u043e')], db_index=True, default=-1, verbose_name='\u0422\u044d\u0433'),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post'),
        ),
    ]
